(function (){
  var u=true,x=null,y=false,z,E=this;function aa(a,f,g){a=a.split(".");g=g||E;!(a[0]in g)&&g.execScript&&g.execScript("var "+a[0]);for(var j;a.length&&(j=a.shift());)if(!a.length&&f!==undefined)g[j]=f;else g=g[j]?g[j]:g[j]={}}function F(){}
function I(a){var f=typeof a;if(f=="object")if(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.toString.call(a)=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(!(a instanceof Object)&&(Object.prototype.toString.call(a)=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call")))return"function"}else return"null";
else if(f=="function"&&typeof a.call=="undefined")return"object";return f}function L(a){return typeof a=="string"}var N="closure_uid_"+Math.floor(Math.random()*2147483648).toString(36),ba=0;function O(a,f){function g(){}g.prototype=f.prototype;a.K=f.prototype;a.prototype=new g;a.prototype.constructor=a};function fa(a){this.stack=Error().stack||"";if(a)this.message=String(a)}O(fa,Error);fa.prototype.name="CustomError";function ga(a){for(var f=1;f<arguments.length;f++){var g=String(arguments[f]).replace(/\$/g,"$$$$");a=a.replace(/\%s/,g)}return a}function ha(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")}
function ia(a,f){for(var g=0,j=ha(String(a)).split("."),l=ha(String(f)).split("."),h=Math.max(j.length,l.length),k=0;g==0&&k<h;k++){var n=j[k]||"",r=l[k]||"",q=RegExp("(\\d*)(\\D*)","g"),J=RegExp("(\\d*)(\\D*)","g");do{var A=q.exec(n)||["","",""],s=J.exec(r)||["","",""];if(A[0].length==0&&s[0].length==0)break;g=ja(A[1].length==0?0:parseInt(A[1],10),s[1].length==0?0:parseInt(s[1],10))||ja(A[2].length==0,s[2].length==0)||ja(A[2],s[2])}while(g==0)}return g}
function ja(a,f){if(a<f)return-1;else if(a>f)return 1;return 0};function ka(a,f){f.unshift(a);fa.call(this,ga.apply(x,f));f.shift();this.X=a}O(ka,fa);ka.prototype.name="AssertionError";function la(a,f){if(!a){var g=Array.prototype.slice.call(arguments,2),j="Assertion failed";if(f){j+=": "+f;var l=g}throw new ka(""+j,l||[]);}return a};var P=Array.prototype,ma=P.indexOf?function(a,f,g){la(a.length!=x);return P.indexOf.call(a,f,g)}:function(a,f,g){g=g==x?0:g<0?Math.max(0,a.length+g):g;if(L(a)){if(!L(f)||f.length!=1)return-1;return a.indexOf(f,g)}for(g=g;g<a.length;g++)if(g in a&&a[g]===f)return g;return-1},na=P.forEach?function(a,f,g){la(a.length!=x);P.forEach.call(a,f,g)}:function(a,f,g){for(var j=a.length,l=L(a)?a.split(""):a,h=0;h<j;h++)h in l&&f.call(g,l[h],h,a)};var U,oa,pa,qa;function ta(){return E.navigator?E.navigator.userAgent:x}qa=pa=oa=U=y;var ua;if(ua=ta()){var va=E.navigator;U=ua.indexOf("Opera")==0;oa=!U&&ua.indexOf("MSIE")!=-1;pa=!U&&ua.indexOf("WebKit")!=-1;qa=!U&&!pa&&va.product=="Gecko"}var wa=U,V=oa,xa=qa,ya=pa,za=E.navigator,Aa=(za&&za.platform||"").indexOf("Mac")!=-1,Ba;
a:{var Ca="",W;if(wa&&E.opera){var Da=E.opera.version;Ca=typeof Da=="function"?Da():Da}else{if(xa)W=/rv\:([^\);]+)(\)|;)/;else if(V)W=/MSIE\s+([^\);]+)(\)|;)/;else if(ya)W=/WebKit\/(\S+)/;if(W){var Ea=W.exec(ta());Ca=Ea?Ea[1]:""}}if(V){var Fa,Ga=E.document;Fa=Ga?Ga.documentMode:undefined;if(Fa>parseFloat(Ca)){Ba=String(Fa);break a}}Ba=Ca}var Ia={};function Ja(a){return Ia[a]||(Ia[a]=ia(Ba,a)>=0)};var Ka;!V||Ja("9");V&&Ja("9");function La(a){this.P=a||E.document||document};var Ma=function(a){return function(){return a}}(u);/*
 Portions of this code are from the Dojo Toolkit, received by
 The Closure Library Authors under the BSD license. All other code is
 Copyright 2005-2009 The Closure Library Authors. All Rights Reserved.

 The "New" BSD License:

 Copyright (c) 2005-2009, The Dojo Foundation
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 Redistributions of source code must retain the above copyright notice, this
 list of conditions and the following disclaimer.
 Redistributions in binary form must reproduce the above copyright notice,
 this list of conditions and the following disclaimer in the documentation
 and/or other materials provided with the distribution.
 Neither the name of the Dojo Foundation nor the names of its contributors
 may be used to endorse or promote products derived from this software
 without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
var Na=function(){function a(b,c){if(!b)return[];if(b.constructor==Array)return b;if(!L(b))return[b];if(L(c)){c=L(c)?document.getElementById(c):c;if(!c)return[]}c=c||document;var d=c.ownerDocument||c.documentElement;Q=c.contentType&&c.contentType=="application/xml"||wa&&(c.doctype||d.toString()=="[object XMLDocument]")||!!d&&(V?d.xml:c.xmlVersion||d.xmlVersion);if((d=j(b)(c))&&d.q)return d;return f(d)}function f(b){if(b&&b.q)return b;var c=[];if(!b||!b.length)return c;b[0]&&c.push(b[0]);if(b.length<
2)return c;M++;if(V&&Q){var d=M+"";b[0].setAttribute("_zipIdx",d);for(var e=1,i;i=b[e];e++){b[e].getAttribute("_zipIdx")!=d&&c.push(i);i.setAttribute("_zipIdx",d)}}else if(V&&b.L)try{for(e=1;i=b[e];e++)ra(i)&&c.push(i)}catch(m){}else{if(b[0])b[0]._zipIdx=M;for(e=1;i=b[e];e++){b[e]._zipIdx!=M&&c.push(i);i._zipIdx=M}}return c}function g(b,c){if(!c)return 1;var d=yb(b);if(!c[d])return c[d]=1;return 0}function j(b,c){if(cb){var d=db[b];if(d&&!c)return d}if(d=eb[b])return d;d=b.charAt(0);var e=-1==b.indexOf(" ");
if(b.indexOf("#")>=0&&e)c=u;if(cb&&!c&&">~+".indexOf(d)==-1&&(!V||b.indexOf(":")==-1)&&!(fb&&b.indexOf(".")>=0)&&b.indexOf(":contains")==-1&&b.indexOf("|=")==-1){var i=">~+".indexOf(b.charAt(b.length-1))>=0?b+" *":b;return db[b]=function(B){try{if(!(9==B.nodeType||e))throw"";var o=B.querySelectorAll(i);if(V)o.L=u;else o.q=u;return o}catch(p){return j(b,u)(B)}}}else{var m=b.split(/\s*,\s*/);return eb[b]=m.length<2?l(b):function(B){for(var o=0,p=[],v;v=m[o++];)p=p.concat(l(v)(B));return p}}}function l(b){var c=
gb(ha(b));if(c.length==1){var d=h(c[0]);return function(e){if(e=d(e,[]))e.q=u;return e}}return function(e){e=R(e);for(var i,m,B=c.length,o,p,v=0;v<B;v++){p=[];i=c[v];m=e.length-1;if(m>0){o={};p.q=u}m=h(i);for(var t=0;i=e[t];t++)m(i,p,o);if(!p.length)break;e=p}return p}}function h(b){var c=hb[b.i];if(c)return c;var d=b.D;d=d?d.r:"";var e=q(b,{h:1}),i="*"==b.a,m=document.getElementsByClassName;if(d){m={h:1};if(i)m.a=1;e=q(b,m);if("+"==d)c=r(e);else if("~"==d)c=n(e);else if(">"==d)c=k(e)}else if(b.id){e=
!b.G&&i?Ma:q(b,{h:1,id:1});c=function(o,p){var v;v=o?new La(o.nodeType==9?o:o.ownerDocument||o.document):Ka||(Ka=new La);var t=b.id;if((v=L(t)?v.P.getElementById(t):t)&&e(v))if(9==o.nodeType)return R(v,p);else{for(t=v.parentNode;t;){if(t==o)break;t=t.parentNode}if(t)return R(v,p)}}}else if(m&&/\{\s*\[native code\]\s*\}/.test(String(m))&&b.b.length&&!fb){e=q(b,{h:1,b:1,id:1});var B=b.b.join(" ");c=function(o,p){for(var v=R(0,p),t,K=0,D=o.getElementsByClassName(B);t=D[K++];)e(t,o)&&v.push(t);return v}}else if(!i&&
!b.G)c=function(o,p){for(var v=R(0,p),t,K=0,D=o.getElementsByTagName(b.t());t=D[K++];)v.push(t);return v};else{e=q(b,{h:1,a:1,id:1});c=function(o,p){for(var v=R(0,p),t,K=0,D=o.getElementsByTagName(b.t());t=D[K++];)e(t,o)&&v.push(t);return v}}return hb[b.i]=c}function k(b){b=b||Ma;return function(c,d,e){for(var i=0,m=c[ib];c=m[i++];)if(ca(c)&&(!e||g(c,e))&&b(c,i))d.push(c);return d}}function n(b){return function(c,d,e){for(c=c[da];c;){if(ca(c)){if(e&&!g(c,e))break;b(c)&&d.push(c)}c=c[da]}return d}}
function r(b){return function(c,d,e){for(;c=c[da];)if(!(sa&&!ra(c))){if((!e||g(c,e))&&b(c))d.push(c);break}return d}}function q(b,c){if(!b)return Ma;c=c||{};var d=x;c.h||(d=S(d,ra));if(!c.a)if(b.a!="*")d=S(d,function(e){return e&&e.tagName==b.t()});c.b||na(b.b,function(e,i){var m=RegExp("(?:^|\\s)"+e+"(?:\\s|$)");d=S(d,function(B){return m.test(B.className)});d.W=i});c.f||na(b.f,function(e){var i=e.name;if(Ha[i])d=S(d,Ha[i](i,e.value))});c.l||na(b.l,function(e){var i,m=e.s;if(e.type&&jb[e.type])i=
jb[e.type](m,e.u);else if(m.length)i=zb(m);if(i)d=S(d,i)});if(!c.id)if(b.id)d=S(d,function(e){return!!e&&e.id==b.id});d||"default"in c||(d=Ma);return d}function J(b){return s(b)%2}function A(b){return!(s(b)%2)}function s(b){var c=b.parentNode,d=0,e=c[ib],i=b._i||-1,m=c._l||-1;if(!e)return-1;e=e.length;if(m==e&&i>=0&&m>=0)return i;c._l=e;i=-1;for(c=c.firstElementChild||c.firstChild;c;c=c[da])if(ca(c)){c._i=++d;if(b===c)i=d}return i}function G(b){for(;b=b[da];)if(ca(b))return y;return u}function kb(b){for(;b=
b[Ab];)if(ca(b))return y;return u}function T(b,c){if(!b)return"";if(c=="class")return b.className||"";if(c=="for")return b.htmlFor||"";if(c=="style")return b.style.cssText||"";return(Q?b.getAttribute(c):b.getAttribute(c,2))||""}function ra(b){return 1==b.nodeType}function S(b,c){if(!b)return c;if(!c)return b;return function(){return b.apply(window,arguments)&&c.apply(window,arguments)}}function gb(b){function c(){if(v>=0){w.id=d(v,C).replace(/\\/g,"");v=-1}if(t>=0){var ea=t==C?x:d(t,C);if(">~+".indexOf(ea)<
0)w.a=ea;else w.r=ea;t=-1}if(p>=0){w.b.push(d(p+1,C).replace(/\\/g,""));p=-1}}function d(ea,Bb){return ha(b.slice(ea,Bb))}b+=">~+".indexOf(b.slice(-1))>=0?" * ":" ";for(var e=[],i=-1,m=-1,B=-1,o=-1,p=-1,v=-1,t=-1,K="",D="",lb,C=0,Cb=b.length,w=x,H=x;K=D,D=b.charAt(C),C<Cb;C++)if(K!="\\"){if(!w){lb=C;w={i:x,f:[],l:[],b:[],a:x,r:x,id:x,t:function(){return Q?this.R:this.a}};t=C}if(i>=0)if(D=="]"){if(H.s)H.u=d(B||i+1,C);else H.s=d(i+1,C);if(i=H.u)if(i.charAt(0)=='"'||i.charAt(0)=="'")H.u=i.slice(1,-1);
w.l.push(H);H=x;i=B=-1}else{if(D=="="){B="|~^$*".indexOf(K)>=0?K:"";H.type=B+D;H.s=d(i+1,C-B.length);B=C+1}}else if(m>=0){if(D==")"){if(o>=0)H.value=d(m+1,C);o=m=-1}}else if(D=="#"){c();v=C+1}else if(D=="."){c();p=C}else if(D==":"){c();o=C}else if(D=="["){c();i=C;H={}}else if(D=="("){if(o>=0){H={name:d(o+1,C),value:x};w.f.push(H)}m=C}else if(D==" "&&K!=D){c();o>=0&&w.f.push({name:d(o+1,C)});w.G=w.f.length||w.l.length||w.b.length;w.Y=w.i=d(lb,C);w.R=w.a=w.r?x:w.a||"*";if(w.a)w.a=w.a.toUpperCase();
if(e.length&&e[e.length-1].r){w.D=e.pop();w.i=w.D.i+" "+w.i}e.push(w);w=x}}return e}function R(b,c){var d=c||[];b&&d.push(b);return d}var fb=ya&&document.compatMode=="BackCompat",ib=document.firstChild.children?"children":"childNodes",Q=y,jb={"*=":function(b,c){return function(d){return T(d,b).indexOf(c)>=0}},"^=":function(b,c){return function(d){return T(d,b).indexOf(c)==0}},"$=":function(b,c){return function(d){d=" "+T(d,b);return d.lastIndexOf(c)==d.length-c.length}},"~=":function(b,c){var d=" "+
c+" ";return function(e){return(" "+T(e,b)+" ").indexOf(d)>=0}},"|=":function(b,c){c=" "+c;return function(d){d=" "+T(d,b);return d==c||d.indexOf(c+"-")==0}},"=":function(b,c){return function(d){return T(d,b)==c}}},sa=typeof document.firstChild.nextElementSibling=="undefined",da=!sa?"nextElementSibling":"nextSibling",Ab=!sa?"previousElementSibling":"previousSibling",ca=sa?ra:Ma,Ha={checked:function(){return function(b){return b.checked||b.attributes.checked}},"first-child":function(){return kb},"last-child":function(){return G},
"only-child":function(){return function(b){if(!kb(b))return y;if(!G(b))return y;return u}},empty:function(){return function(b){var c=b.childNodes;for(b=b.childNodes.length-1;b>=0;b--){var d=c[b].nodeType;if(d===1||d==3)return y}return u}},contains:function(b,c){var d=c.charAt(0);if(d=='"'||d=="'")c=c.slice(1,-1);return function(e){return e.innerHTML.indexOf(c)>=0}},not:function(b,c){var d=gb(c)[0],e={h:1};if(d.a!="*")e.a=1;if(!d.b.length)e.b=1;var i=q(d,e);return function(m){return!i(m)}},"nth-child":function(b,
c){if(c=="odd")return J;else if(c=="even")return A;if(c.indexOf("n")!=-1){var d=c.split("n",2),e=d[0]?d[0]=="-"?-1:parseInt(d[0],10):1,i=d[1]?parseInt(d[1],10):0,m=0,B=-1;if(e>0)if(i<0)i=i%e&&e+i%e;else{if(i>0){if(i>=e)m=i-i%e;i%=e}}else if(e<0){e*=-1;if(i>0){B=i;i%=e}}if(e>0)return function(p){p=s(p);return p>=m&&(B<0||p<=B)&&p%e==i};else c=i}var o=parseInt(c,10);return function(p){return s(p)==o}}},zb=V?function(b){var c=b.toLowerCase();if(c=="class")b="className";return function(d){return Q?d.getAttribute(b):
d[b]||d[c]}}:function(b){return function(c){return c&&c.getAttribute&&c.hasAttribute(b)}},hb={},eb={},db={},cb=!!document.querySelectorAll&&(!ya||Ja("526")),M=0,yb=V?function(b){return Q?b.getAttribute("_uid")||b.setAttribute("_uid",++M)||M:b.uniqueID}:function(b){return b._uid||(b._uid=++M)};a.f=Ha;return a}();aa("goog.dom.query",Na,void 0);aa("goog.dom.query.pseudos",Na.f,void 0);var Oa;!V||Ja("9");V&&Ja("8");function Pa(){}Pa.prototype.A=y;Pa.prototype.m=function(){if(!this.A){this.A=u;this.g()}};Pa.prototype.g=function(){};function Qa(a,f){this.type=a;this.currentTarget=this.target=f}O(Qa,Pa);Qa.prototype.g=function(){delete this.type;delete this.target;delete this.currentTarget};Qa.prototype.v=y;Qa.prototype.T=u;function Ra(a,f){a&&this.n(a,f)}O(Ra,Qa);z=Ra.prototype;z.target=x;z.relatedTarget=x;z.offsetX=0;z.offsetY=0;z.clientX=0;z.clientY=0;z.screenX=0;z.screenY=0;z.button=0;z.keyCode=0;z.charCode=0;z.ctrlKey=y;z.altKey=y;z.shiftKey=y;z.metaKey=y;z.S=y;z.B=x;
z.n=function(a,f){var g=this.type=a.type;this.target=a.target||a.srcElement;this.currentTarget=f;var j=a.relatedTarget;if(j){if(xa)try{j=j.nodeName&&j}catch(l){j=x}}else if(g=="mouseover")j=a.fromElement;else if(g=="mouseout")j=a.toElement;this.relatedTarget=j;this.offsetX=a.offsetX!==undefined?a.offsetX:a.layerX;this.offsetY=a.offsetY!==undefined?a.offsetY:a.layerY;this.clientX=a.clientX!==undefined?a.clientX:a.pageX;this.clientY=a.clientY!==undefined?a.clientY:a.pageY;this.screenX=a.screenX||0;
this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(g=="keypress"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.S=Aa?a.metaKey:a.ctrlKey;this.B=a;delete this.T;delete this.v};z.g=function(){Ra.K.g.call(this);this.relatedTarget=this.currentTarget=this.target=this.B=x};function Sa(){}var Ta=0;z=Sa.prototype;z.key=0;z.k=y;z.w=y;z.n=function(a,f,g,j,l,h){if(I(a)=="function")this.F=u;else if(a&&a.handleEvent&&I(a.handleEvent)=="function")this.F=y;else throw Error("Invalid listener argument");this.o=a;this.J=f;this.src=g;this.type=j;this.capture=!!l;this.C=h;this.w=y;this.key=++Ta;this.k=y};z.handleEvent=function(a){if(this.F)return this.o.call(this.C||this.src,a);return this.o.handleEvent.call(this.o,a)};function X(a,f){this.H=f;this.e=[];if(a>this.H)throw Error("[goog.structs.SimplePool] Initial cannot be greater than max");for(var g=0;g<a;g++)this.e.push(this.c?this.c():{})}O(X,Pa);X.prototype.c=x;X.prototype.z=x;function Ua(a){if(a.e.length)return a.e.pop();return a.c?a.c():{}}function Va(a,f){a.e.length<a.H?a.e.push(f):Wa(a,f)}function Wa(a,f){if(a.z)a.z(f);else{var g=I(f);if(g=="object"||g=="array"||g=="function")if(I(f.m)=="function")f.m();else for(var j in f)delete f[j]}}
X.prototype.g=function(){X.K.g.call(this);for(var a=this.e;a.length;)Wa(this,a.pop());delete this.e};var Xa;var Ya=(Xa="ScriptEngine"in E&&E.ScriptEngine()=="JScript")?E.ScriptEngineMajorVersion()+"."+E.ScriptEngineMinorVersion()+"."+E.ScriptEngineBuildVersion():"0";var Za,$a,ab,bb,mb,nb,ob,pb,qb,rb,sb;
(function(){function a(){return{d:0,j:0}}function f(){return[]}function g(){function s(G){return k.call(s.src,s.key,G)}return s}function j(){return new Sa}function l(){return new Ra}var h=Xa&&!(ia(Ya,"5.7")>=0),k;nb=function(s){k=s};if(h){Za=function(){return Ua(n)};$a=function(s){Va(n,s)};ab=function(){return Ua(r)};bb=function(s){Va(r,s)};mb=function(){return Ua(q)};ob=function(){Va(q,g())};pb=function(){return Ua(J)};qb=function(s){Va(J,s)};rb=function(){return Ua(A)};sb=function(s){Va(A,s)};var n=
new X(0,600);n.c=a;var r=new X(0,600);r.c=f;var q=new X(0,600);q.c=g;var J=new X(0,600);J.c=j;var A=new X(0,600);A.c=l}else{Za=a;$a=F;ab=f;bb=F;mb=g;ob=F;pb=j;qb=F;rb=l;sb=F}})();var Y={},Z={},$={},tb={};
function ub(a,f,g,j,l){if(f)if(I(f)=="array"){for(var h=0;h<f.length;h++)ub(a,f[h],g,j,l);return x}else{j=!!j;var k=Z;f in k||(k[f]=Za());k=k[f];if(!(j in k)){k[j]=Za();k.d++}k=k[j];var n=a[N]||(a[N]=++ba),r;k.j++;if(k[n]){r=k[n];for(h=0;h<r.length;h++){k=r[h];if(k.o==g&&k.C==l){if(k.k)break;return r[h].key}}}else{r=k[n]=ab();k.d++}h=mb();h.src=a;k=pb();k.n(g,h,a,f,j,l);g=k.key;h.key=g;r.push(k);Y[g]=k;$[n]||($[n]=ab());$[n].push(k);if(a.addEventListener){if(a==E||!a.N)a.addEventListener(f,h,j)}else a.attachEvent(vb(f),
h);return g}else throw Error("Invalid event type");}function wb(a,f,g,j){if(!j.p)if(j.I){for(var l=0,h=0;l<j.length;l++)if(j[l].k){var k=j[l].J;k.src=x;ob(k);qb(j[l])}else{if(l!=h)j[h]=j[l];h++}j.length=h;j.I=y;if(h==0){bb(j);delete Z[a][f][g];Z[a][f].d--;if(Z[a][f].d==0){$a(Z[a][f]);delete Z[a][f];Z[a].d--}if(Z[a].d==0){$a(Z[a]);delete Z[a]}}}}function vb(a){if(a in tb)return tb[a];return tb[a]="on"+a}
function xb(a,f,g,j,l){var h=1;f=f[N]||(f[N]=++ba);if(a[f]){a.j--;a=a[f];if(a.p)a.p++;else a.p=1;try{for(var k=a.length,n=0;n<k;n++){var r=a[n];if(r&&!r.k)h&=Db(r,l)!==y}}finally{a.p--;wb(g,j,f,a)}}return Boolean(h)}
function Db(a,f){var g=a.handleEvent(f);if(a.w){var j=a.key;if(Y[j]){var l=Y[j];if(!l.k){var h=l.src,k=l.type,n=l.J,r=l.capture;if(h.removeEventListener){if(h==E||!h.N)h.removeEventListener(k,n,r)}else h.detachEvent&&h.detachEvent(vb(k),n);h=h[N]||(h[N]=++ba);n=Z[k][r][h];if($[h]){var q=$[h],J=ma(q,l);if(J>=0){la(q.length!=x);P.splice.call(q,J,1)}q.length==0&&delete $[h]}l.k=u;n.I=u;wb(k,r,h,n);delete Y[j]}}}return g}
nb(function(a,f){if(!Y[a])return u;var g=Y[a],j=g.type,l=Z;if(!(j in l))return u;l=l[j];var h,k;if(Oa===undefined)Oa=V&&!E.addEventListener;if(Oa){var n;if(!(n=f))a:{n="window.event".split(".");for(var r=E;h=n.shift();)if(r[h])r=r[h];else{n=x;break a}n=r}h=n;n=u in l;r=y in l;if(n){if(h.keyCode<0||h.returnValue!=undefined)return u;a:{var q=y;if(h.keyCode==0)try{h.keyCode=-1;break a}catch(J){q=u}if(q||h.returnValue==undefined)h.returnValue=u}}q=rb();q.n(h,this);h=u;try{if(n){for(var A=ab(),s=q.currentTarget;s;s=
s.parentNode)A.push(s);k=l[u];k.j=k.d;for(var G=A.length-1;!q.v&&G>=0&&k.j;G--){q.currentTarget=A[G];h&=xb(k,A[G],j,u,q)}if(r){k=l[y];k.j=k.d;for(G=0;!q.v&&G<A.length&&k.j;G++){q.currentTarget=A[G];h&=xb(k,A[G],j,y,q)}}}else h=Db(g,q)}finally{if(A){A.length=0;bb(A)}q.m();sb(q)}return h}j=new Ra(f,this);try{h=Db(g,j)}finally{j.m()}return h});function Eb(a){this.M=a||{};this.U=this.M.switcherSelector||Fb;this.V=Na(this.U);na(this.V,this.O,this)}aa("gweb.ui.Switcher",Eb,void 0);var Fb="#x-nav select";Eb.prototype.O=function(a){ub(a,"change",this.Q,y,this)};Eb.prototype.Q=function(a){window.location.href=a.target[a.target.selectedIndex].value};
})()
